const $=s=>document.querySelector(s);
const msgs=$("#msgs"),q=$("#q"),send=$("#send"),fileInput=$("#zip"),fileList=$("#list"),fileCount=$("#fileCount");
let projectFiles=[],conversation=[],controller=null;
const GROQ_KEY="aku_groq_api_key",GROQ_MODEL="openai/gpt-oss-20b";
const SYSTEM_PROMPT="You are Aku Code, a practical coding assistant. Use supplied project files when relevant. Be concise and actionable. Use Markdown with **bold**, inline code, and fenced code blocks.";
$("#groqKey").value=sessionStorage.getItem(GROQ_KEY)||localStorage.getItem(GROQ_KEY)||"";
$("#saveGroq").onclick=()=>{const key=$("#groqKey").value.trim();if($("#rememberGroq").checked){key?localStorage.setItem(GROQ_KEY,key):localStorage.removeItem(GROQ_KEY);sessionStorage.removeItem(GROQ_KEY)}else{key?sessionStorage.setItem(GROQ_KEY,key):sessionStorage.removeItem(GROQ_KEY);localStorage.removeItem(GROQ_KEY)}checkConnection()};
function groqKey(){return sessionStorage.getItem(GROQ_KEY)||localStorage.getItem(GROQ_KEY)||""}
function setConnection(ok,text){$("#connectionText").textContent=text;$("#connectionText").previousElementSibling.classList.toggle("online",ok)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function inline(s){let x=esc(s);x=x.replace(/\`([^\`]+)\`/g,'<code class="inline-code">$1</code>');x=x.replace(/\*\*([^*\n]+)\*\*/g,"<strong>$1</strong>");x=x.replace(/__([^_\n]+)__/g,"<strong>$1</strong>");return x}
function md(text){const lines=String(text||"").replace(/\r/g,"").split("\n"),out=[];let code=false,lang="",buf=[],para=[];
const fp=()=>{if(para.length){out.push("<p>"+inline(para.join("\n")).replace(/\n/g,"<br>")+"</p>");para=[]}};
const fc=()=>{if(buf.length||code){out.push('<div class="code-block"><div class="code-head"><span>'+esc(lang||"code")+'</span><button type="button" class="copy-code">Copy</button></div><pre><code>'+esc(buf.join("\n"))+'</code></pre></div>');buf=[]}};
for(const line of lines){if(/^\s*\`\`\`/.test(line)){if(!code){fp();code=true;lang=line.replace(/^\s*\`\`\`/,"").trim()}else{code=false;fc()}continue}if(code)buf.push(line);else if(!line.trim())fp();else if(/^\s*[-*]\s+/.test(line)){fp();out.push("<p>• "+inline(line.replace(/^\s*[-*]\s+/,""))+"</p>")}else para.push(line)}
if(code)fc();else fp();return out.join("")||"<span></span>"}
function scroll(){msgs.lastElementChild?.scrollIntoView({behavior:"smooth",block:"nearest"})}
function userMsg(text){const w=document.createElement("div");w.className="msg user";w.innerHTML='<div class="msg-meta">You</div><div>'+esc(text).replace(/\n/g,"<br>")+"</div>";msgs.appendChild(w);scroll()}
function aiMsg(){const w=document.createElement("div");w.className="msg assistant streaming";w.innerHTML='<div class="msg-meta">Aku Code · Groq · LIVE</div><div class="markdown"></div>';msgs.appendChild(w);scroll();return{w,b:w.querySelector(".markdown")}}
function finish(item,text){item.w.classList.remove("streaming");item.b.innerHTML=md(text)+'<div class="msg-actions"><button type="button" class="copy-response">Copy response</button></div>';scroll()}
function errorMsg(text){const w=document.createElement("div");w.className="msg assistant";w.innerHTML='<div class="msg-meta">Aku Code</div><div class="msg-error">'+esc(text)+"</div>";msgs.appendChild(w);scroll()}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");["chat","files","about"].forEach(v=>$("#"+v).classList.toggle("hide",v!==b.dataset.v))});
function checkConnection(){const ok=!!groqKey();setConnection(ok,ok?"Groq key ready":"Groq key not configured");$("#health").textContent=ok?"Groq ready · "+GROQ_MODEL:"Add your Groq API key in Settings"}
async function ask(){if(send.dataset.streaming==="1"){controller?.abort();return}const text=q.value.trim();if(!text)return;userMsg(text);q.value="";const key=groqKey();if(!key){errorMsg("Groq API key is not configured. Open Settings and add your Groq key.");return}
send.dataset.streaming="1";send.classList.add("stop");send.textContent="Stop ■";controller=new AbortController();const item=aiMsg();let full="";
const projectContext=projectFiles.length?"\n\nPROJECT FILES:\n"+projectFiles.map(f=>"--- "+f.path+" ---\n"+f.content).join("\n\n"):"";
const history=[...conversation,{role:"user",content:text+projectContext}].slice(-12);
try{const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+key},body:JSON.stringify({model:GROQ_MODEL,messages:[{role:"system",content:SYSTEM_PROMPT},...history],temperature:.2,stream:true}),signal:controller.signal});
if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.error?.message||"Groq request failed")}
const reader=r.body.getReader(),decoder=new TextDecoder();let buffer="";
while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const parts=buffer.split("\n\n");buffer=parts.pop()||"";for(const part of parts){for(const line of part.split("\n")){if(!line.startsWith("data:"))continue;const data=line.slice(5).trim();if(!data||data==="[DONE]")continue;let j;try{j=JSON.parse(data)}catch{continue}const delta=j.choices?.[0]?.delta?.content||"";if(delta){full+=delta;item.b.innerHTML=md(full)+'<span class="stream-cursor"></span>';scroll()}}}}
if(!full)full="No response.";finish(item,full);conversation.push({role:"user",content:text},{role:"assistant",content:full});conversation=conversation.slice(-12)
}catch(e){if(e.name==="AbortError"){if(full)finish(item,full);else item.w.remove()}else{item.w.remove();errorMsg("Groq request failed: "+e.message)}}finally{controller=null;send.dataset.streaming="0";send.classList.remove("stop");send.textContent="Send ↵"}}
send.onclick=ask;q.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}};
msgs.addEventListener("click",async e=>{const b=e.target.closest("button");if(!b)return;const block=b.closest(".code-block");if(b.classList.contains("copy-code")&&block){try{await navigator.clipboard.writeText(block.querySelector("code").textContent);b.textContent="Copied ✓";setTimeout(()=>b.textContent="Copy",1000)}catch{b.textContent="Copy failed"}}if(b.classList.contains("copy-response")){const body=b.closest(".msg").querySelector(".markdown");try{await navigator.clipboard.writeText(body.innerText.replace("Copy response",""));b.textContent="Copied ✓";setTimeout(()=>b.textContent="Copy response",1000)}catch{b.textContent="Copy failed"}}});
fileInput.onchange=async e=>{const file=e.target.files[0];if(!file)return;fileCount.textContent="Reading "+file.name+"…";projectFiles=[];try{if(!window.JSZip)throw new Error("ZIP reader unavailable");const zip=await JSZip.loadAsync(file),allowed=/\.(ts|tsx|js|jsx|json|md|css|html|py|java|go|rs|php|sql|yaml|yml|toml)$/i;for(const [path,entry] of Object.entries(zip.files)){if(entry.dir||projectFiles.length>=80||path.split("/").some(x=>["node_modules",".git",".next","dist","build"].includes(x))||!allowed.test(path))continue;const content=await entry.async("string");if(content.length<=120000)projectFiles.push({path,content})}fileList.innerHTML="";projectFiles.forEach(f=>{const row=document.createElement("div");row.className="file";row.textContent="📄 "+f.path;fileList.appendChild(row)});if(!projectFiles.length)fileList.textContent="No supported source files found.";fileCount.textContent=projectFiles.length+" files attached";$("#projectName").textContent=file.name.replace(/\.zip$/i,"");document.querySelector('[data-v="files"]').click()}catch(err){fileCount.textContent="Could not read ZIP";fileList.textContent=err.message||"ZIP error"}};
checkConnection();