const $=s=>document.querySelector(s);
const msgs=$("#msgs"),q=$("#q"),send=$("#send"),fileInput=$("#zip"),fileList=$("#list"),fileCount=$("#fileCount");
let projectFiles=[];
const GROQ_KEY="aku_groq_api_key";
const GROQ_MODEL="openai/gpt-oss-20b";
const SYSTEM_PROMPT="You are Aku Code, a practical coding assistant. Use the supplied project files as context when relevant. Do not claim to execute code, edit files, or access systems you cannot access. Give concise, actionable answers.";
$("#groqKey").value=sessionStorage.getItem(GROQ_KEY)||localStorage.getItem(GROQ_KEY)||"";
$("#saveGroq").onclick=()=>{const key=$("#groqKey").value.trim();if($("#rememberGroq").checked){if(key)localStorage.setItem(GROQ_KEY,key);else localStorage.removeItem(GROQ_KEY);sessionStorage.removeItem(GROQ_KEY)}else{if(key)sessionStorage.setItem(GROQ_KEY,key);else sessionStorage.removeItem(GROQ_KEY);localStorage.removeItem(GROQ_KEY)}checkConnection()};
function groqKey(){return sessionStorage.getItem(GROQ_KEY)||localStorage.getItem(GROQ_KEY)||""}
function setConnection(online,text){$("#connectionText").textContent=text;$("#connectionText").previousElementSibling.classList.toggle("online",online)}
function addMessage(text,type="assistant",label){const wrap=document.createElement("div");wrap.className="msg "+type;const meta=document.createElement("div");meta.className="msg-meta";meta.textContent=label||"Aku Code";const body=document.createElement("div");body.textContent=text;wrap.append(meta,body);msgs.appendChild(wrap);wrap.scrollIntoView({behavior:"smooth",block:"nearest"})}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");["chat","files","about"].forEach(v=>$("#"+v).classList.toggle("hide",v!==b.dataset.v))});
function checkConnection(){const ok=!!groqKey();setConnection(ok,ok?"Groq key ready":"Groq key not configured");$("#health").textContent=ok?"Groq ready · "+GROQ_MODEL:"Add your Groq API key in Settings"}
async function ask(){const text=q.value.trim();if(!text||send.disabled)return;addMessage(text,"user","You");q.value="";send.disabled=true;send.textContent="Thinking…";const key=groqKey();if(!key){addMessage("Groq API key is not configured. Open Settings and add your Groq key.");send.disabled=false;send.textContent="Send ↵";return}const projectContext=projectFiles.length?"\n\nPROJECT FILES:\n"+projectFiles.map(f=>"--- "+f.path+" ---\n"+f.content).join("\n\n"):"";try{const r=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+key},body:JSON.stringify({model:GROQ_MODEL,messages:[{role:"system",content:SYSTEM_PROMPT},{role:"user",content:text+projectContext}],temperature:0.2})});const d=await r.json();if(!r.ok)throw new Error(d.error?.message||"Groq request failed");addMessage(d.choices?.[0]?.message?.content||"No response.","assistant","Aku Code · Groq")}catch(e){addMessage("Groq request failed: "+e.message)}finally{send.disabled=false;send.textContent="Send ↵"}}
send.onclick=ask;q.onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}};
fileInput.onchange=async e=>{const file=e.target.files[0];if(!file)return;fileCount.textContent="Reading "+file.name+"…";projectFiles=[];try{if(!window.JSZip)throw new Error("ZIP reader unavailable");const zip=await JSZip.loadAsync(file);const allowed=/\.(ts|tsx|js|jsx|json|md|css|html|py|java|go|rs|php|sql|yaml|yml|toml)$/i;for(const [path,entry] of Object.entries(zip.files)){if(entry.dir||projectFiles.length>=80||path.split("/").some(x=>["node_modules",".git",".next","dist","build"].includes(x))||!allowed.test(path))continue;const content=await entry.async("string");if(content.length<=120000)projectFiles.push({path,content})}fileList.innerHTML="";if(!projectFiles.length)fileList.textContent="No supported source files found.";else projectFiles.forEach(f=>{const row=document.createElement("div");row.className="file";row.textContent="📄 "+f.path;fileList.appendChild(row)});fileCount.textContent=projectFiles.length+" files attached";$("#projectName").textContent=file.name.replace(/\.zip$/i,"");document.querySelector('[data-v="files"]').click()}catch(err){fileCount.textContent="Could not read ZIP";fileList.textContent=err.message||"ZIP error"}};
checkConnection();