"use client";
import {useState} from "react";
export default function Home(){
 const [prompt,setPrompt]=useState(""); const [answer,setAnswer]=useState(""); const [loading,setLoading]=useState(false);
 async function ask(){if(!prompt.trim()||loading)return;setLoading(true);setAnswer("");try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})});const d=await r.json();setAnswer(d.answer||d.error||"No response.");}catch{setAnswer("Request failed. Check the server configuration.");}finally{setLoading(false)}}
 return <main style={{minHeight:"100vh",display:"grid",gridTemplateColumns:"240px 1fr"}}>
 <aside style={{borderRight:"1px solid #202227",padding:20,background:"#0c0d10"}}><h1 style={{margin:0,fontSize:24}}>Aku Code</h1><p style={{color:"#888",fontSize:13}}>AI coding workspace</p><div style={{marginTop:35,color:"#aaa",fontSize:14}}>EXPLORER</div><div style={{marginTop:14,padding:10,borderRadius:8,background:"#17191e"}}>📁 my-project</div><div style={{padding:"9px 10px",color:"#999"}}>📄 README.md</div><div style={{padding:"9px 10px",color:"#999"}}>📄 package.json</div></aside>
 <section style={{display:"flex",flexDirection:"column",minWidth:0}}><header style={{height:60,borderBottom:"1px solid #202227",display:"flex",alignItems:"center",padding:"0 24px",justifyContent:"space-between"}}><span style={{color:"#aaa"}}>Workspace</span><span style={{fontSize:13,color:"#777"}}>Aku Apps</span></header>
 <div style={{flex:1,maxWidth:900,width:"100%",margin:"0 auto",padding:"60px 24px"}}><div style={{textAlign:"center"}}><div style={{fontSize:48}}>⌘</div><h2 style={{fontSize:32,margin:"12px 0"}}>Build with Aku Code</h2><p style={{color:"#8b8d94"}}>Ask about code, debug errors, explain files, or plan a feature.</p></div>
 <div style={{marginTop:45,border:"1px solid #292c33",borderRadius:14,background:"#101216",overflow:"hidden"}}><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Ask Aku Code anything about your project..." rows={5} style={{width:"100%",resize:"vertical",background:"transparent",border:0,outline:0,color:"#fff",padding:16}}/><div style={{display:"flex",justifyContent:"flex-end",padding:10}}><button onClick={ask} disabled={loading||!prompt.trim()} style={{border:0,borderRadius:8,padding:"9px 16px",background:"#fff",color:"#000"}}>{loading?"Thinking...":"Send ↵"}</button></div></div>
 {answer&&<pre style={{whiteSpace:"pre-wrap",marginTop:24,padding:18,border:"1px solid #292c33",borderRadius:12,background:"#0d0f12",lineHeight:1.6,color:"#ddd"}}>{answer}</pre>}</div></section></main>
}